### ISSUE TITLE
feat: game "sorting"

### ISSUE THREAD

**Issue by RusKhass** [Sapariyeva/esdp-ajs15-team-2#1]
Написать игру "Сортировка"

### План решения:
Игра представляет из себя набор колоды карточек и области с определенным контентом, в которые необходимо разместить соответствующие карточки из колоды.

1. Использовать классы
2. Использовать **JavaScript**
3. Для карточек можно использовать линки на изображения, либо на ваше усмотрение
4. Для каждого класса написать тесты, используя **jest**
5. Достаточно 3-х областей и 3-х карточек

### Мотивация
Клиенту необходима игра "Сортировка" в приложении "ИгроВУЗ", данная задача в рамках подготовки к разработке приложения

### Критерии приёмки:
> Игру запускается в терминале

> Пользователю предлагается разместить карточки в соответствующие области (т.к. игра "текстовая" под цифрами 1, 2 и 3 из областей с линками на изображения контента подставить карточки с соответствующими линками на изображения из так называемой колоды)

> Вывести в консоль сообщения о начале игры, при успешном и неуспешном размещениях

> Все тесты успешно проходят 

Планируемое время работы: 3часа

**Comment by AlisherZhanabayev** [comment]
Используемое время: 4ч
