### ISSUE TITLE
Локализация ошибок и сообщений с бэкенда

### ISSUE THREAD

**Issue by StanislavPark** [Sapariyeva/esdp-ajs15-team-2#19]
# Локализация ошибок и сообщений с бэкенда

План решения:

1. Цель: Реализовать локализацию для поддержки нескольких языков в сообщениях об ошибках и других ответах бэкенда.
2. Языки: Начать с английского и русского.
3. Библиотека: Использовать библиотеку i18n для управления переводами.
4. Настройка: Интегрировать библиотеку i18n в проект на Node.js и Express.
5. Конфигурация: Создать конфигурационные файлы для переводов на английский и русский языки.
6. Middleware: Реализовать middleware для определения языковых предпочтений пользователя и предоставления локализованных сообщений.
7. Интеграция: Заменить жестко закодированные сообщения об ошибках и другие ответы на локализованные сообщения.
8. Тестирование: Убедиться, что все конечные точки возвращают сообщения на соответствующем языке в зависимости от предпочтений пользователя.

### Мотивация:
Поддержка локализации позволяет сделать приложение доступным для большего числа пользователей, улучшая пользовательский опыт за счет предоставления информации на их родном языке.

Критерии приёмки:

>1.Файлы локализации: Созданы и правильно структурированы файлы переводов на английский и русский языки.
>2.Middleware: Middleware правильно определяет языковые предпочтения пользователя и предоставляет соответствующие переводы.
>3.Конечные точки: Все конечные точки возвращают локализованные сообщения об ошибках и ответы.
>4.Тестирование: Ручное тестирование конечных точек для обоих языков для проверки корректной локализации.

**Comment by RusKhass** [comment]
Время работы: 9 часов 20 минут

**Comment by RusKhass** [comment]
+ 40 минут
