### ISSUE TITLE
feat: game "Show"

### ISSUE THREAD

**Issue by RusKhass** [Sapariyeva/esdp-ajs15-team-2#2]
Написать игру "Покажи"

### План решения:
Игра представляет из себя набор карточек и текстовым сообщением, в котором описана ситуация на одной из приведенных карточек (глагол), которую следует выбрать.

1. Использовать классы
2. Использовать **JavaScript**
3. Для карточек можно использовать линки на изображения, либо на ваше усмотрение
4. Для каждого класса написать тесты, используя **jest**
5. Достаточно 3-х карточек

### Мотивация
Клиенту необходима игра "Покажи" в приложении "ИгроВУЗ", данная задача в рамках подготовки к разработке приложения

### Критерии приёмки:
> Игру запускается в терминале

> Пользователю предлагается выбрать одну из трех карточек, на которой изображено действие, описанное в задании 

> Вывести в консоль сообщения о начале игры и задании, при успешном и неуспешном выборах карточки  

> Все тесты успешно проходят

Планируемое время работы:
2 часа

**Comment by NarimB** [comment]
Потраченное время 4 часа
