### ISSUE TITLE
Аутентификация через Google

### ISSUE THREAD

**Issue by StanislavPark** [Sapariyeva/esdp-ajs15-team-2#20]
# Аутентификация через Google

План решения:

1. Цель: Реализовать аутентификацию пользователей через Google для входа и регистрации.
2. Библиотека: Использовать passport.js вместе с passport-google-oauth20 для аутентификации через Google.
3. Настройка: Интегрировать passport.js и passport-google-oauth20 в проект на Node.js и Express.
4. Конфигурация: Настроить passport.js с учетными данными Google.
5. Управление сессиями: Убедиться, что управление сессиями пользователей правильно работает после аутентификации.
6. Тестирование: Проверить процесс аутентификации через Google от начала до конца, чтобы убедиться в правильной работе.

### Мотивация:
Добавление аутентификации через Google упрощает процесс входа и регистрации для пользователей, уменьшая трение и повышая удобство использования приложения.

Критерии приёмки:

>1.Данные пользователя: Данные пользователя корректно извлекаются и сохраняются в базе данных после аутентификации.
>2.Сессия: Управление сессиями пользователей корректно работает, обеспечивая доступ к защищённым конечным точкам.
>3.Тестирование: Процесс аутентификации через Google успешно завершён, и доступ к защищённым маршрутам проверен.

**Comment by RusKhass** [comment]
Время работы: 5 часов
