### ISSUE TITLE
feat: authorization

### ISSUE THREAD

**Issue by RusKhass** [Sapariyeva/esdp-ajs15-team-2#3]
Написать базовый функционал авторизации без хранения данных в базе данных

### План решения:
1. Использовать классы
2. Использовать **JavaScript**
3. Для каждого класса написать тесты, используя **jest**
4. Для регистрации необходимы логин, email и пароль
5. Для входа логин и пароль

### Мотивация
Клиенту необходим функционал авторизации в приложении "ИгроВУЗ", данная задача в рамках подготовки к разработке приложения

### Критерии приёмки:
> Код запускается в терминале

> Пользователю необходимо пройти регистрацию, для этого необходимо ввести логин, email и пароль

> Затем произвести вход, используя логин и пароль

> Вывод в консоль все необходимые сообщения для пользователя (успечная и неуспечная регистрация, успешный и неуспешный вход и т.д.)

> Все тесты успешно проходят

Планируемое время работы:

2 часа 30 минут

**Comment by ShlyundtDiana** [comment]
фактическое время 2 часа 20 минут
