### ISSUE TITLE
feat: game "Sorting" - using React

### ISSUE THREAD

**Issue by RusKhass** [Sapariyeva/esdp-ajs15-team-2#5]
Написать игру "Сортировка"

### План решения:
Игра представляет из себя набор колоды карточек и области с определенным контентом, в которые необходимо разместить соответствующие карточки из колоды.

1. Использовать классы
2. Использовать **JavaScript**
3. Для карточек и областей использовать изображения
4. Для каждого класса написать тесты, используя **jest**
5. Достаточно 3-х областей и 3-х карточек
6. Для фронтенда использовать React
7. Добавить конфигуратор (см. макет)
8. Добавить возможность добавления новых карточек

### Мотивация
Клиенту необходима игра "Сортировка" в приложении "ИгроВУЗ", данная задача в рамках подготовки к разработке приложения

### Критерии приёмки:
> В браузере открываю ссылку http://localhost:5173

> Вижу интерфейс игры с карточками и областями

> Пользователь может перетаскивать карточки и размещать их в соответствующих областях

> Вывести сообщения при успешном и неуспешном размещениях

> Все тесты успешно проходят 

Планируемое время работы: 8ч

**Comment by AlisherZhanabayev** [comment]
Используемое время работы: 11ч
