### ISSUE TITLE
feat: Create a Design System in CSS/SCSS and a Component Library

### ISSUE THREAD

**Issue by ShlyundtDiana** [Sapariyeva/esdp-ajs15-team-2#8]
#### 1. Определить стилистические принципы:
-    Цветовая палитра
-    Типографика
-    Отступы, размеры и сетка
-    Принципы иконографии

#### 2. Создать базовые стили для HTML-элементов:
-    Заголовки, параграфы, списки, ссылки, таблицы

#### 3. Разработать библиотеку компонентов:
- Кнопки
- Поля ввода (текстовые, пароля, текстовые области)
- Формы
- Карточки
- Модальные окна
- Навигационные элементы (меню, вкладки)
- Сообщения (ошибки, предупреждения, успехи)

#### 4. Организация структуры файлов SCSS:
- Переменные (цвета, шрифты, размеры)
- Миксины и функции
- Частичные файлы для отдельных компонентов и элементов
- Главный файл для сборки всех стилей

#### 5. Интеграция с проектом:
- Подключить и настроить CSS-препроцессор (SCSS) в проекте
- Импортировать библиотеку компонентов в проект

### Мотивация
Для проекта необходима единая и последовательная дизайн система и библиотека компонентов для приложения "ИгроВУЗ", чтобы обеспечить согласованность, упростить разработку и поддержку кода. Данная задача важна для подготовки к разработке приложения и для расширяемости дизайна и компонентов.

### Критерии приёмки:
> В браузере открываю ссылку http://localhost:5173

> При загрузке страницы отображаются основные компоненты интерфейса с применением новой дизайн системы

> Все элементы интерфейса стилизованы согласно макета (цветовая палитра, типографика, отступы и т.д.)

> Компоненты интерфейса (кнопки, поля ввода, формы, карточки, модальные окна и т.д.) выглядят и функционируют корректно

> Переменные, миксины и функции SCSS используются для стандартизации и упрощения стилей

> Структура файлов SCSS организована логично и поддерживает масштабируемость

> Библиотека компонентов успешно интегрирована в проект

Планируемое время работы:

**Comment by AlisherZhanabayev** [comment]
Используемое время: 18h
